Add channeltalk
UnicornPeople/skill-coach pull request #1
Opened 2024-02-09 11:08 UTC by yenoss

2024-02-09 12:21 UTC, JSpiner requested changes

2024-02-09 12:21 UTC, JSpiner commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
이거 디펜던시 package.json에 추가되어야할거 같네요

2024-02-09 12:22 UTC, JSpiner commented on src/index.tsx
> +  "pluginKey":"52bce222-811d-4bb8-9d56-ecff2504be8e",
얘 노출되어도 딱히 상관없는거죠?

2024-02-09 13:15 UTC, yenoss commented on src/index.tsx
> +  "pluginKey":"52bce222-811d-4bb8-9d56-ecff2504be8e",
네 크게 상관없을거같아요. env로 뺄려고하는데 잘안되더군여...ㅠ

2024-02-09 13:19 UTC, yenoss commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
이거 package.json에 추가가안되있던대 혹시 별도로 패키지를 추가하는 cmd가있나요?

2024-02-09 13:19 UTC, yenoss commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
그리고 node modules는 제거하는게 어떤가요? 각 환경에서 다운받아서 쓰면될거같은데, 가끔 해당 존재한느 폴더때문에 
npm install이 안되는경우가있어요.

2024-02-09 13:29 UTC, JSpiner commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
> 이거 package.json에 추가가안되있던대 혹시 별도로 패키지를 추가하는 cmd가있나요?

npm install로 안되나요? 지금은 에러나네요

<img width="1394" alt="스크린샷 2024-02-09 22 29 16" src="https://github.com/UnicornPeople/skill-coach/assets/5474864/3571031f-f3f0-4dc7-a317-74f52b137b59">

2024-02-09 13:32 UTC, JSpiner commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
```shell
$ npm install @channel.io/channel-web-sdk-loader
```

혹시 `-g` 옵션 붙이셨나요? -g 없이 위 스크립트 실행하면 package.json에 아래처럼 추가될거에여

```json
   "private": true,
   "homepage": "https://ro0opf.github.io/skill-coach",
   "dependencies": {
+    "@channel.io/channel-web-sdk-loader": "^1.1.7",
     "@testing-library/jest-dom": "^5.17.0",
     "@testing-library/react": "^13.4.0",
     "@testing-library/user-event": "^13.5.0",

```

> 그리고 node modules는 제거하는게 어떤가요? 각 환경에서 다운받아서 쓰면될거같은데, 가끔 해당 존재한느 폴더때문에
> npm install이 안되는경우가있어요.

저도 요게 맞는거같아요~~ 셋팅하신 @ro0opf 확인 부탁드려요

2024-02-09 13:39 UTC, yenoss commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
네 수정했습니다

2024-02-09 13:39 UTC, yenoss commented on src/index.tsx
> +import * as ChannelService from '@channel.io/channel-web-sdk-loader';
노드 모듈지우는건 다른 pr에서하시죠

2024-02-11 13:54 UTC, JSpiner approved these changes

2024-02-11 14:20 UTC, merged